Hubble parametrized
cosmology-api/cosmology-api pull request #31
Opened 2023-03-02 18:57 UTC by nstarman

I think the `StandardCosmology` should only be an inheritance of other components. Therefore, we should separate out the Hubble (and later the Tcmb) pieces. This PR makes the Protocol ``HubbleParametrized`` which holds the Hubble info.

## PR Checklist

- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

2023-03-02 21:05 UTC, ntessore commented
Can you explain this change a little more? As I understand it, a Hubble parameter comes with having a scale factor, which comes with having a redshift... So in this picture, every FLRW cosmology should be `HubbleParametrized` intrinsically.

2023-03-03 03:31 UTC, nstarman commented
As in, we should package it into ``FLRWBackground``?

2023-03-03 09:41 UTC, ntessore commented
I just don't see how it could be separate from the distance functions. The Hubble function is the connection between redshift and physical time, from which you get the comoving distance.

Hm, ok, on the implementation side, I see how a cosmology instance might not expose the `H0` and `H(z)` details, in which case one would have to manually differentiate the comoving distance somehow to get it back ...

Maybe the name sent me in the wrong direction, because it's not parametrised by the Hubble function. Perhaps `HubbleParameter` as an alternative?

2023-03-04 21:44 UTC, nstarman commented
> Maybe the name sent me in the wrong direction, because it's not parametrised by the Hubble function. Perhaps `HubbleParameter` as an alternative?

That sounds reasonable, or what about ``HasHubbleParameter`` or ``SupportsHubbleParameter``?

2023-03-04 21:47 UTC, nstarman commented
Also, then I suppose we would separate out ``HasTCMB``?
I've been trying to decide whether ``HasTCMB`` would require support for photons? Technically the CMB background temperature is the temperature of the photons, so if the are no photons.... OTOH often in simple models, e.g. only matter and dark energy we still talk about the background temperature.

2023-03-04 22:00 UTC, ntessore commented
I think if we want to separate everything, then yes, we should separate truly everything.

I like the `HasX` names, but then we probably also want to change all the components (again) to be `HasXComponent`.

2023-03-07 19:31 UTC, nstarman commented
Ok. Followup PR will separate out the Tcmb and rename the components.

2023-03-07 21:11 UTC, nstarman commented
@ntessore, ready for review.

One thing I've considered changing w.r.t astropy is ``inv_efunc`` to ``efunc_inv``. I think this makes the relationship to ``efunc`` more explicit. What do you think? Also is ``efunc`` a good name? What would be a better alternative?

2023-03-07 22:23 UTC, ntessore commented
> What are your thoughts on `HasTcmb` requiring (or not) `HasPhotonComponent` ?

I don't see a benefit to requiring it. It might not be exposed by the underlying cosmology object, similar to the point of this PR.

> One thing I've considered changing w.r.t astropy is `inv_efunc` to `efunc_inv`. I think this makes the relationship to `efunc` more explicit. What do you think? Also is `efunc` a good name? What would be a better alternative?

I find both `inv_efunc` and `efunc_inv` poor choices because it makes me think that is an inverse function returning a redshift given a value. Also, what's the computational advantage of having it? I can only think of sticking it directly into a numerical quadrature, but if a cosmology implementation wants to do that internally, the method doesn't have to be exposed.

2023-03-07 22:30 UTC, ntessore submitted a review, later dismissed
LGTM. I would not have put this into its own submodule, it can just live next to the main cosmology implementation, to save the time for one more import.

2023-03-07 22:32 UTC, nstarman commented
When mypyc has fixed some issues with runtime-checkable protocols (in their radar) we can compile this whole library into c-wheels. Long term, speed will never be an issue.

2023-03-07 22:36 UTC, nstarman commented
> I don't see a benefit to requiring it. It might not be exposed by the underlying cosmology object, similar to the point of this PR.

SGTM

> I find both `inv_efunc` and `efunc_inv` poor choices because it makes me think that is an inverse function returning a redshift given a value. Also, what's the computational advantage of having it? I can only think of sticking it directly into a numerical quadrature, but if a cosmology implementation wants to do that internally, the method doesn't have to be exposed.

For v0.1 we can remove `inv_efunc`. Punt the decision down the road a bit.
What about the name `efunc`?

2023-03-08 01:01 UTC, ntessore commented
> For v0.1 we can remove `inv_efunc`. Punt the decision down the road a bit. What about the name `efunc`?

Sounds good. I don't know of any other, more recognisable name for `efunc`. CCL calls it `h_over_h0` but I don't find that better.

2023-03-08 05:01 UTC, nstarman commented
> > For v0.1 we can remove `inv_efunc`. Punt the decision down the road a bit. What about the name `efunc`?
> 
> Sounds good. I don't know of any other, more recognisable name for `efunc`. CCL calls it `h_over_h0` but I don't find that better.

We have `H` for the Hubble Parameter. What about `EH`?

2023-03-08 13:21 UTC, ntessore commented
> > > For v0.1 we can remove `inv_efunc`. Punt the decision down the road a bit. What about the name `efunc`?
> > 
> > 
> > Sounds good. I don't know of any other, more recognisable name for `efunc`. CCL calls it `h_over_h0` but I don't find that better.
> 
> We have `H` for the Hubble Parameter. What about `EH`?

Those uppercase function names violate PEP 8 and look like constants, so that makes `efunc` superior in my opinion.

2023-03-08 15:20 UTC, nstarman commented
> Those uppercase function names violate PEP 8 and look like constants, so that makes `efunc` superior in my opinion.

😮‍💨. Yeah, it's a problem with `H`, but thankfully not `H0`. My issues with ``efunc`` are that it feels silly to name a function `func`, even more so when it's technically a *method*.

2023-03-08 16:18 UTC, ntessore requested changes

2023-03-08 16:18 UTC, ntessore commented on src/cosmology/api/_extras.py
> +    r"""The cosmology contains global curvature, described by :math:`Omega_K`."""
```suggestion
    r"""The cosmology has methods to retrieve the Hubble parameter :math:`H`."""
```

2023-03-08 16:24 UTC, nstarman commented on src/cosmology/api/_extras.py
> +    r"""The cosmology contains global curvature, described by :math:`Omega_K`."""
😆

2023-03-08 19:03 UTC, ntessore approved these changes

2023-03-08 19:06 UTC, merged